/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const CatalogCategory = IDL.Record({
  'name' : IDL.Text,
  'items' : IDL.Vec(Item),
});
export const Catalog = IDL.Vec(CatalogCategory);

export const idlService = IDL.Service({
  'getCatalog' : IDL.Func([], [Catalog], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const CatalogCategory = IDL.Record({
    'name' : IDL.Text,
    'items' : IDL.Vec(Item),
  });
  const Catalog = IDL.Vec(CatalogCategory);
  
  return IDL.Service({ 'getCatalog' : IDL.Func([], [Catalog], ['query']) });
};

export const init = ({ IDL }) => { return []; };